version: 2
jobs:
  build:
    filters:
      branches:
        only: master
    working_directory: ~/app
    docker:
      - image: circleci/node:4.8.2
    steps:
      - checkout
      - run:
          name: install-yarn
          command: 'sudo npm i -g yarn@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: yarn-install
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: lint
          command: yarn lint
