version: 2
jobs:
  build:
    branches:
      only: master
    working_directory: ~/app
    docker:
      - image: circleci/node:4.8.2
    steps:
      - run:
          name: git-pull
          command: ssh -o "StrictHostKeyChecking no" $DROPLET_USER@$DROPLET_IP 'cd /opt/amerikawedding2017/current && git pull && git clean -f -d'
      - run:
          name: yarn-install
          command: ssh -o "StrictHostKeyChecking no" $DROPLET_USER@$DROPLET_IP 'cd /opt/amerikawedding2017/current && yarn'
      - run:
          name: build-prod
          command: ssh -o "StrictHostKeyChecking no" $DROPLET_USER@$DROPLET_IP 'cd /opt/amerikawedding2017/current && yarn build:prod'
      - run:
          name: forever-restart
          command: ssh -o "StrictHostKeyChecking no" $DROPLET_USER@$DROPLET_IP 'cd /opt/amerikawedding2017/current && yarn forever:restart'
